"""Demo data source — realistic product data for testing the full pipeline.

Uses real-world product examples from Chinese marketplaces.
This source is used to validate the pipeline while we build
proper scrapers (1688 requires headless browser).
"""

from __future__ import annotations

import random
from datetime import datetime, timezone

from src.models import RawProduct

from .base import BaseCollector

# Category-specific placeholder images
# Using picsum.photos for reliable Telegram delivery
CATEGORY_IMAGES: dict[str, str] = {
    "electronics": "https://picsum.photos/600/600?random=1",
    "gadgets": "https://picsum.photos/600/600?random=2",
    "home": "https://picsum.photos/600/600?random=3",
    "phone_accessories": "https://picsum.photos/600/600?random=4",
    "car_accessories": "https://picsum.photos/600/600?random=5",
    "led_lighting": "https://picsum.photos/600/600?random=6",
    "beauty_devices": "https://picsum.photos/600/600?random=7",
    "smart_home": "https://picsum.photos/600/600?random=8",
    "outdoor": "https://picsum.photos/600/600?random=9",
    "toys": "https://picsum.photos/600/600?random=10",
    "health": "https://picsum.photos/600/600?random=11",
    "kitchen": "https://picsum.photos/600/600?random=12",
    "pet": "https://picsum.photos/600/600?random=13",
    "sport": "https://picsum.photos/600/600?random=14",
    "office": "https://picsum.photos/600/600?random=15",
    "kids": "https://picsum.photos/600/600?random=16",
}

# Realistic product data based on actual trending items on Chinese marketplaces
DEMO_PRODUCTS: list[dict] = [
    {
        "title_cn": "无线蓝牙耳机 降噪 运动耳机 2025新款",
        "title_ru": "Беспроводные Bluetooth наушники с шумоподавлением, спортивные, новинка 2025",
        "category": "electronics",
        "price_cny": 28.5,
        "min_order": 50,
        "sales_volume": 15200,
        "sales_trend": 45.0,
        "rating": 4.7,
        "supplier_name": "Shenzhen AudioTech Co.",
        "supplier_years": 6,
        "source_url": "https://www.alibaba.com/product-detail/A6R-TWS-Wireless-Bluetooth-Earphones-Noise_1600409619233.html",
        "wb_keyword": "наушники беспроводные",
        "wb_est_price": 2500.0,
    },
    {
        "title_cn": "迷你投影仪 家用 高清 便携式 手机投影",
        "title_ru": "Мини-проектор портативный для дома, HD, подключение к телефону",
        "category": "electronics",
        "price_cny": 185.0,
        "min_order": 10,
        "sales_volume": 4800,
        "sales_trend": 78.0,
        "rating": 4.5,
        "supplier_name": "Guangzhou OptiView Technology",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/product-detail/J9-Mini-Projector-Portable-HD-1080P_700008956698.html",
        "wb_keyword": "мини проектор",
        "wb_est_price": 7500.0,
    },
    {
        "title_cn": "智能手表 心率监测 血氧检测 运动手环",
        "title_ru": "Смарт-часы с мониторингом пульса и уровня кислорода, фитнес-браслет",
        "category": "electronics",
        "price_cny": 42.0,
        "min_order": 30,
        "sales_volume": 22000,
        "sales_trend": 32.0,
        "rating": 4.6,
        "supplier_name": "Dongguan WearTech Ltd.",
        "supplier_years": 8,
        "source_url": "https://www.alibaba.com/product-detail/T900-Ultra-Smart-Watch-Fitness-Tracker_1600666108639.html",
        "wb_keyword": "смарт часы",
        "wb_est_price": 3200.0,
    },
    {
        "title_cn": "车载手机支架 磁吸 导航支架 汽车用品",
        "title_ru": "Автомобильный магнитный держатель для телефона, крепление для навигации",
        "category": "car_accessories",
        "price_cny": 8.5,
        "min_order": 100,
        "sales_volume": 35000,
        "sales_trend": 15.0,
        "rating": 4.8,
        "supplier_name": "Yiwu AutoParts Trading",
        "supplier_years": 11,
        "source_url": "https://www.alibaba.com/product-detail/Magnetic-Car-Phone-Holder-Universal-Wall_60806795667.html",
        "wb_keyword": "держатель телефона авто",
        "wb_est_price": 550.0,
    },
    {
        "title_cn": "USB充电暖手宝 移动电源 二合一 冬季热销",
        "title_ru": "USB-грелка для рук + повербанк 2-в-1, зимний хит продаж",
        "category": "gadgets",
        "price_cny": 22.0,
        "min_order": 50,
        "sales_volume": 18500,
        "sales_trend": 120.0,
        "rating": 4.4,
        "supplier_name": "Shenzhen GiftPower Co.",
        "supplier_years": 5,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=USB+hand+warmer+power+bank",
        "wb_keyword": "грелка для рук",
        "wb_est_price": 1500.0,
    },
    {
        "title_cn": "电动牙刷 超声波 充电式 成人 防水",
        "title_ru": "Электрическая зубная щётка ультразвуковая, перезаряжаемая, водонепроницаемая",
        "category": "home",
        "price_cny": 35.0,
        "min_order": 20,
        "sales_volume": 12000,
        "sales_trend": 55.0,
        "rating": 4.6,
        "supplier_name": "Ningbo OralCare Technology",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=electric+toothbrush+ultrasonic+rechargeable",
        "wb_keyword": "электрическая зубная щетка",
        "wb_est_price": 2200.0,
    },
    {
        "title_cn": "宠物自动喂食器 智能 定时 猫粮狗粮",
        "title_ru": "Автоматическая кормушка для животных, умная, с таймером, для кошек и собак",
        "category": "home",
        "price_cny": 68.0,
        "min_order": 10,
        "sales_volume": 8900,
        "sales_trend": 95.0,
        "rating": 4.3,
        "supplier_name": "Foshan PetSmart Electronics",
        "supplier_years": 3,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=automatic+pet+feeder+smart+timer",
        "wb_keyword": "автокормушка кошка",
        "wb_est_price": 3800.0,
    },
    {
        "title_cn": "便携式榨汁杯 充电 随身 果汁机 小型",
        "title_ru": "Портативный блендер-бутылка, перезаряжаемый, мини-соковыжималка",
        "category": "home",
        "price_cny": 25.0,
        "min_order": 50,
        "sales_volume": 28000,
        "sales_trend": 40.0,
        "rating": 4.5,
        "supplier_name": "Zhongshan KitchenTech Co.",
        "supplier_years": 9,
        "source_url": "https://www.alibaba.com/product-detail/Blender-USB-Rechargeable-Portable-Blender-Bottles_1600988152618.html",
        "wb_keyword": "портативный блендер",
        "wb_est_price": 1800.0,
    },
    {
        "title_cn": "LED化妆镜 台式 带灯 触控调光 桌面镜",
        "title_ru": "LED-зеркало для макияжа настольное с подсветкой, сенсорная регулировка яркости",
        "category": "beauty_devices",
        "price_cny": 32.0,
        "min_order": 30,
        "sales_volume": 9500,
        "sales_trend": 60.0,
        "rating": 4.7,
        "supplier_name": "Shenzhen BeautyLight Ltd.",
        "supplier_years": 5,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=LED+makeup+mirror+touch+dimming",
        "wb_keyword": "зеркало с подсветкой",
        "wb_est_price": 2000.0,
    },
    {
        "title_cn": "太阳能户外灯 庭院灯 防水 感应灯 花园装饰",
        "title_ru": "Солнечный садовый светильник уличный, водонепроницаемый, с датчиком движения",
        "category": "outdoor",
        "price_cny": 15.0,
        "min_order": 100,
        "sales_volume": 42000,
        "sales_trend": 25.0,
        "rating": 4.4,
        "supplier_name": "Jiangmen SolarBright Co.",
        "supplier_years": 12,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=solar+garden+light+outdoor+sensor",
        "wb_keyword": "садовый светильник",
        "wb_est_price": 800.0,
    },
    {
        "title_cn": "无线充电器 桌面 快充 适用苹果安卓 折叠",
        "title_ru": "Беспроводная зарядка настольная, быстрая, для iPhone/Android, складная",
        "category": "phone_accessories",
        "price_cny": 18.0,
        "min_order": 50,
        "sales_volume": 31000,
        "sales_trend": 20.0,
        "rating": 4.6,
        "supplier_name": "Shenzhen ChargePro Technology",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=wireless+charger+foldable+fast+charging",
        "wb_keyword": "беспроводная зарядка",
        "wb_est_price": 1200.0,
    },
    {
        "title_cn": "颈挂式风扇 便携 USB充电 免手持 夏季爆款",
        "title_ru": "Шейный вентилятор портативный, USB-зарядка, hands-free, летний хит",
        "category": "gadgets",
        "price_cny": 19.5,
        "min_order": 50,
        "sales_volume": 55000,
        "sales_trend": 180.0,
        "rating": 4.3,
        "supplier_name": "Zhongshan CoolBreeze Ltd.",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=neck+fan+portable+USB+rechargeable",
        "wb_keyword": "вентилятор шейный",
        "wb_est_price": 1200.0,
    },
    # --- Batch 2: 20 more products across diverse categories ---
    {
        "title_cn": "筋膜枪 迷你 便携 肌肉放松 按摩器",
        "title_ru": "Массажный пистолет мини, портативный, для расслабления мышц",
        "category": "health",
        "price_cny": 45.0,
        "min_order": 20,
        "sales_volume": 32000,
        "sales_trend": 85.0,
        "rating": 4.5,
        "supplier_name": "Shenzhen BodyCare Technology",
        "supplier_years": 5,
        "source_url": "https://www.alibaba.com/product-detail/Cheap-Portable-Mini-Massage-Gun-Electric_1600412194708.html",
        "wb_keyword": "массажный пистолет",
        "wb_est_price": 3500.0,
    },
    {
        "title_cn": "桌面加湿器 USB 迷你 静音 办公室",
        "title_ru": "Настольный увлажнитель воздуха USB, мини, бесшумный, для офиса",
        "category": "home",
        "price_cny": 16.0,
        "min_order": 50,
        "sales_volume": 25000,
        "sales_trend": 35.0,
        "rating": 4.4,
        "supplier_name": "Foshan AirPure Co.",
        "supplier_years": 6,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=USB+mini+humidifier+desktop+silent",
        "wb_keyword": "увлажнитель воздуха мини",
        "wb_est_price": 900.0,
    },
    {
        "title_cn": "露营灯 LED 充电 户外 帐篷灯 便携",
        "title_ru": "Кемпинговый фонарь LED, перезаряжаемый, для палатки, портативный",
        "category": "outdoor",
        "price_cny": 12.0,
        "min_order": 100,
        "sales_volume": 38000,
        "sales_trend": 50.0,
        "rating": 4.6,
        "supplier_name": "Ningbo OutdoorGear Ltd.",
        "supplier_years": 8,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=camping+lantern+LED+rechargeable+portable",
        "wb_keyword": "кемпинговый фонарь",
        "wb_est_price": 700.0,
    },
    {
        "title_cn": "电子秤 厨房 食物秤 高精度 烘焙称",
        "title_ru": "Кухонные электронные весы, высокая точность, для выпечки",
        "category": "home",
        "price_cny": 9.0,
        "min_order": 100,
        "sales_volume": 45000,
        "sales_trend": 10.0,
        "rating": 4.7,
        "supplier_name": "Yongkang ScalePro Co.",
        "supplier_years": 15,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=kitchen+scale+electronic+precision+baking",
        "wb_keyword": "кухонные весы",
        "wb_est_price": 600.0,
    },
    {
        "title_cn": "手机散热器 半导体 制冷 游戏散热背夹",
        "title_ru": "Кулер для смартфона полупроводниковый, охлаждение для игр",
        "category": "phone_accessories",
        "price_cny": 25.0,
        "min_order": 30,
        "sales_volume": 19000,
        "sales_trend": 110.0,
        "rating": 4.3,
        "supplier_name": "Shenzhen CoolGame Technology",
        "supplier_years": 3,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=phone+cooler+semiconductor+gaming",
        "wb_keyword": "кулер для телефона",
        "wb_est_price": 1500.0,
    },
    {
        "title_cn": "自动感应泡沫洗手机 智能 免接触 皂液器",
        "title_ru": "Автоматический дозатор мыла-пены, сенсорный, бесконтактный",
        "category": "home",
        "price_cny": 28.0,
        "min_order": 30,
        "sales_volume": 16000,
        "sales_trend": 65.0,
        "rating": 4.6,
        "supplier_name": "Wenzhou SmartHome Co.",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=automatic+foam+soap+dispenser+touchless",
        "wb_keyword": "дозатор мыла автоматический",
        "wb_est_price": 1800.0,
    },
    {
        "title_cn": "迷你缝纫机 家用 便携式 电动 小型",
        "title_ru": "Мини швейная машинка портативная, электрическая, для дома",
        "category": "home",
        "price_cny": 35.0,
        "min_order": 20,
        "sales_volume": 11000,
        "sales_trend": 40.0,
        "rating": 4.2,
        "supplier_name": "Taizhou SewEasy Ltd.",
        "supplier_years": 10,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=mini+sewing+machine+portable+electric",
        "wb_keyword": "мини швейная машинка",
        "wb_est_price": 2500.0,
    },
    {
        "title_cn": "车载吸尘器 无线 大吸力 便携 小型",
        "title_ru": "Автомобильный пылесос беспроводной, мощный, портативный, компактный",
        "category": "car_accessories",
        "price_cny": 42.0,
        "min_order": 20,
        "sales_volume": 14000,
        "sales_trend": 55.0,
        "rating": 4.4,
        "supplier_name": "Suzhou CleanDrive Technology",
        "supplier_years": 6,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=car+vacuum+cleaner+wireless+portable",
        "wb_keyword": "автопылесос беспроводной",
        "wb_est_price": 2800.0,
    },
    {
        "title_cn": "头戴式蓝牙耳机 无线 降噪 重低音 游戏",
        "title_ru": "Накладные Bluetooth наушники, беспроводные, шумоподавление, басы, для игр",
        "category": "electronics",
        "price_cny": 38.0,
        "min_order": 30,
        "sales_volume": 20000,
        "sales_trend": 30.0,
        "rating": 4.5,
        "supplier_name": "Dongguan SoundMax Ltd.",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=over+ear+bluetooth+headphones+gaming+bass",
        "wb_keyword": "наушники накладные",
        "wb_est_price": 2800.0,
    },
    {
        "title_cn": "智能体脂秤 家用 电子秤 精准 蓝牙",
        "title_ru": "Умные весы с анализом тела, электронные, Bluetooth, точные",
        "category": "health",
        "price_cny": 22.0,
        "min_order": 50,
        "sales_volume": 27000,
        "sales_trend": 25.0,
        "rating": 4.6,
        "supplier_name": "Zhongshan HealthScale Co.",
        "supplier_years": 9,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=smart+body+fat+scale+bluetooth",
        "wb_keyword": "умные весы",
        "wb_est_price": 1600.0,
    },
    {
        "title_cn": "电动指甲磨甲器 美甲 打磨机 抛光 便携",
        "title_ru": "Электрическая пилка для ногтей, маникюрный аппарат, полировка, портативная",
        "category": "beauty_devices",
        "price_cny": 15.0,
        "min_order": 50,
        "sales_volume": 13000,
        "sales_trend": 45.0,
        "rating": 4.4,
        "supplier_name": "Shenzhen NailPro Co.",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=electric+nail+drill+manicure+portable",
        "wb_keyword": "аппарат для маникюра",
        "wb_est_price": 1100.0,
    },
    {
        "title_cn": "迷你冰箱 车载 小型 冷暖两用 化妆品冰箱",
        "title_ru": "Мини-холодильник для авто и дома, охлаждение/нагрев, для косметики",
        "category": "gadgets",
        "price_cny": 88.0,
        "min_order": 10,
        "sales_volume": 7500,
        "sales_trend": 70.0,
        "rating": 4.3,
        "supplier_name": "Guangzhou CoolBox Technology",
        "supplier_years": 5,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=mini+fridge+car+portable+cooling+warming",
        "wb_keyword": "мини холодильник",
        "wb_est_price": 5500.0,
    },
    {
        "title_cn": "真空密封机 家用 食品 压缩 保鲜机",
        "title_ru": "Вакуумный упаковщик для продуктов, домашний, для хранения и свежести",
        "category": "home",
        "price_cny": 48.0,
        "min_order": 20,
        "sales_volume": 9800,
        "sales_trend": 60.0,
        "rating": 4.5,
        "supplier_name": "Ningbo FreshSeal Co.",
        "supplier_years": 8,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=vacuum+sealer+food+storage+home",
        "wb_keyword": "вакуумный упаковщик",
        "wb_est_price": 3200.0,
    },
    {
        "title_cn": "智能门铃 无线 可视 WiFi 远程对讲",
        "title_ru": "Умный дверной звонок с камерой, WiFi, беспроводной, видеодомофон",
        "category": "electronics",
        "price_cny": 55.0,
        "min_order": 20,
        "sales_volume": 8500,
        "sales_trend": 90.0,
        "rating": 4.4,
        "supplier_name": "Shenzhen SafeHome Technology",
        "supplier_years": 6,
        "source_url": "https://www.alibaba.com/product-detail/V5-Video-Doorbell-Smart-Wireless-WiFi_1600364508458.html",
        "wb_keyword": "умный звонок камера",
        "wb_est_price": 3800.0,
    },
    {
        "title_cn": "折叠键盘 蓝牙 无线 便携 平板手机通用",
        "title_ru": "Складная Bluetooth клавиатура, беспроводная, для планшета и телефона",
        "category": "electronics",
        "price_cny": 32.0,
        "min_order": 30,
        "sales_volume": 6200,
        "sales_trend": 35.0,
        "rating": 4.5,
        "supplier_name": "Shenzhen KeyTech Ltd.",
        "supplier_years": 5,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=folding+bluetooth+keyboard+portable+tablet",
        "wb_keyword": "складная клавиатура",
        "wb_est_price": 2200.0,
    },
    {
        "title_cn": "宠物饮水机 自动循环 过滤 猫咪狗狗 静音",
        "title_ru": "Автоматическая поилка-фонтан для кошек и собак, с фильтрацией, бесшумная",
        "category": "home",
        "price_cny": 35.0,
        "min_order": 20,
        "sales_volume": 21000,
        "sales_trend": 75.0,
        "rating": 4.6,
        "supplier_name": "Foshan PetLife Co.",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=pet+water+fountain+automatic+filter+cat",
        "wb_keyword": "поилка фонтан кошка",
        "wb_est_price": 2400.0,
    },
    {
        "title_cn": "磁悬浮音箱 蓝牙 创意礼品 科技感 桌面",
        "title_ru": "Левитирующая Bluetooth колонка, магнитная, креативный подарок, настольная",
        "category": "gadgets",
        "price_cny": 75.0,
        "min_order": 10,
        "sales_volume": 4200,
        "sales_trend": 130.0,
        "rating": 4.2,
        "supplier_name": "Shenzhen MagicSound Technology",
        "supplier_years": 3,
        "source_url": "https://www.alibaba.com/product-detail/Tiktok-Hot-Selling-Magnetic-Levitating-Blue_1600837884626.html",
        "wb_keyword": "левитирующая колонка",
        "wb_est_price": 4500.0,
    },
    {
        "title_cn": "车载空气净化器 迷你 除味 负离子 USB",
        "title_ru": "Автомобильный очиститель воздуха мини, ионизатор, устранение запахов, USB",
        "category": "car_accessories",
        "price_cny": 18.0,
        "min_order": 50,
        "sales_volume": 17000,
        "sales_trend": 40.0,
        "rating": 4.3,
        "supplier_name": "Guangzhou FreshAir Ltd.",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=car+air+purifier+ionizer+mini+USB",
        "wb_keyword": "ионизатор авто",
        "wb_est_price": 1100.0,
    },
    {
        "title_cn": "便携式烘鞋器 定时 杀菌 除臭 干鞋机",
        "title_ru": "Портативная электросушилка для обуви с таймером, антибактериальная, от запаха",
        "category": "home",
        "price_cny": 14.0,
        "min_order": 50,
        "sales_volume": 23000,
        "sales_trend": 90.0,
        "rating": 4.5,
        "supplier_name": "Yiwu DryComfort Co.",
        "supplier_years": 10,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=shoe+dryer+electric+portable+timer",
        "wb_keyword": "сушилка для обуви",
        "wb_est_price": 800.0,
    },
    {
        "title_cn": "迷你打印机 手机照片 便携 热敏 口袋打印",
        "title_ru": "Мини-принтер для фото со смартфона, термопечать, карманный, портативный",
        "category": "gadgets",
        "price_cny": 52.0,
        "min_order": 20,
        "sales_volume": 10500,
        "sales_trend": 95.0,
        "rating": 4.4,
        "supplier_name": "Shenzhen PrintPocket Technology",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/product-detail/X1-Portable-Mini-Pocket-Photo-Printer_1601403053192.html",
        "wb_keyword": "мини принтер фото",
        "wb_est_price": 3500.0,
    },
    # --- Batch 3: New categories (kitchen, pet, sport, office, kids) ---
    {
        "title_cn": "电动削皮器 自动 多功能 水果蔬菜 厨房神器",
        "title_ru": "Электрическая овощечистка автоматическая, многофункциональная, для кухни",
        "category": "kitchen",
        "price_cny": 18.0,
        "min_order": 50,
        "sales_volume": 26000,
        "sales_trend": 65.0,
        "rating": 4.5,
        "supplier_name": "Yongkang KitchenPro Co.",
        "supplier_years": 8,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=electric+peeler+automatic+kitchen",
        "wb_keyword": "электрическая овощечистка",
        "wb_est_price": 1100.0,
    },
    {
        "title_cn": "手动绞肉机 家用 多功能 搅碎机 厨房工具",
        "title_ru": "Ручная мясорубка многофункциональная, измельчитель, кухонный инструмент",
        "category": "kitchen",
        "price_cny": 15.0,
        "min_order": 50,
        "sales_volume": 31000,
        "sales_trend": 20.0,
        "rating": 4.6,
        "supplier_name": "Zhongshan HomeTool Ltd.",
        "supplier_years": 12,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=manual+meat+grinder+multifunctional+kitchen",
        "wb_keyword": "мясорубка ручная",
        "wb_est_price": 900.0,
    },
    {
        "title_cn": "宠物梳子 去毛梳 猫咪狗狗 自动清理 脱毛刷",
        "title_ru": "Расчёска для животных с самоочисткой, для удаления шерсти кошек и собак",
        "category": "pet",
        "price_cny": 8.0,
        "min_order": 100,
        "sales_volume": 48000,
        "sales_trend": 30.0,
        "rating": 4.7,
        "supplier_name": "Yiwu PetCare Trading",
        "supplier_years": 9,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=pet+brush+self+cleaning+deshedding",
        "wb_keyword": "расческа для собак",
        "wb_est_price": 600.0,
    },
    {
        "title_cn": "宠物GPS追踪器 迷你 定位器 猫咪狗狗 防丢",
        "title_ru": "GPS-трекер для питомцев мини, локатор для кошек и собак, от потери",
        "category": "pet",
        "price_cny": 32.0,
        "min_order": 30,
        "sales_volume": 14000,
        "sales_trend": 95.0,
        "rating": 4.3,
        "supplier_name": "Shenzhen PetTrack Technology",
        "supplier_years": 4,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=pet+GPS+tracker+mini+dog+cat",
        "wb_keyword": "GPS трекер питомец",
        "wb_est_price": 2200.0,
    },
    {
        "title_cn": "瑜伽垫 加厚 防滑 健身垫 运动垫 家用",
        "title_ru": "Коврик для йоги утолщённый, нескользящий, для фитнеса и дома",
        "category": "sport",
        "price_cny": 22.0,
        "min_order": 30,
        "sales_volume": 52000,
        "sales_trend": 15.0,
        "rating": 4.6,
        "supplier_name": "Nantong SportMat Co.",
        "supplier_years": 11,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=yoga+mat+thick+non+slip+fitness",
        "wb_keyword": "коврик для йоги",
        "wb_est_price": 1500.0,
    },
    {
        "title_cn": "跳绳 计数 智能 健身 减肥 成人 无绳",
        "title_ru": "Умная скакалка со счётчиком, для фитнеса и похудения, беспроводная",
        "category": "sport",
        "price_cny": 12.0,
        "min_order": 50,
        "sales_volume": 38000,
        "sales_trend": 55.0,
        "rating": 4.5,
        "supplier_name": "Yiwu FitGear Trading",
        "supplier_years": 6,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=smart+jump+rope+counter+fitness",
        "wb_keyword": "скакалка счётчик",
        "wb_est_price": 800.0,
    },
    {
        "title_cn": "桌面收纳盒 办公 多功能 笔筒 文具 抽屉式",
        "title_ru": "Настольный органайзер для офиса, многофункциональный, с ящиками, для канцелярии",
        "category": "office",
        "price_cny": 14.0,
        "min_order": 50,
        "sales_volume": 19000,
        "sales_trend": 20.0,
        "rating": 4.6,
        "supplier_name": "Ningbo OfficeBox Co.",
        "supplier_years": 10,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=desk+organizer+office+storage+drawer",
        "wb_keyword": "органайзер настольный",
        "wb_est_price": 900.0,
    },
    {
        "title_cn": "儿童早教机 学习机 益智 启蒙 故事机 点读笔",
        "title_ru": "Детская обучающая машинка, развивающая, со сказками и аудиоручкой",
        "category": "kids",
        "price_cny": 35.0,
        "min_order": 20,
        "sales_volume": 16000,
        "sales_trend": 70.0,
        "rating": 4.4,
        "supplier_name": "Shantou EduToy Co.",
        "supplier_years": 7,
        "source_url": "https://www.alibaba.com/trade/search?SearchText=kids+learning+machine+educational+story",
        "wb_keyword": "обучающая машинка детская",
        "wb_est_price": 2500.0,
    },
]


class DemoCollector(BaseCollector):
    """Returns realistic demo products for pipeline testing."""

    async def collect(self, category: str, limit: int = 20) -> list[RawProduct]:
        # Filter by category if specified, otherwise return all
        if category == "all":
            pool = DEMO_PRODUCTS
        else:
            pool = [p for p in DEMO_PRODUCTS if p.get("category") == category]
            if not pool:
                pool = DEMO_PRODUCTS  # fallback to all

        # Shuffle and limit
        selected = random.sample(pool, min(limit, len(pool)))

        products = []
        for item in selected:
            # Get category-specific image or default
            cat = item.get("category", "")
            image_url = CATEGORY_IMAGES.get(cat, CATEGORY_IMAGES.get("electronics", ""))

            products.append(
                RawProduct(
                    source="demo",
                    source_url=item["source_url"],
                    image_url=image_url,
                    title_cn=item["title_cn"],
                    title_ru=item["title_ru"],
                    category=item.get("category", ""),
                    price_cny=item["price_cny"],
                    min_order=item.get("min_order", 1),
                    sales_volume=item.get("sales_volume", 0),
                    sales_trend=item.get("sales_trend", 0),
                    rating=item.get("rating", 0),
                    supplier_name=item.get("supplier_name", ""),
                    supplier_years=item.get("supplier_years", 0),
                    wb_keyword=item.get("wb_keyword", ""),
                    wb_est_price=item.get("wb_est_price", 0.0),
                    collected_at=datetime.now(timezone.utc),
                )
            )

        return products
